name: cmake

on: [push]

jobs:
  build:
    strategy:
        matrix:
          cc: [ gcc, clang ]
    
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v1
    - name: ghaction-cmake
      uses: lpenz/ghaction-cmake@v0.1
      with:
          dependencies: 'zlib1g-dev libpng-dev'
          cc: ${{ matrix.cc }}
