name: cmake

on: [push]

jobs:
  build:
    strategy:
        matrix:
          cc: [ gcc, clang ]
    
    runs-on: ubuntu-latest
      
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Fetch submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: Build with CMake
      uses: lpenz/ghaction-cmake@v0.1
      with:
          dependencies: 'zlib1g-dev libpng-dev'
          cc: ${{ matrix.cc }}
